export const SCREENS = {
  LOGIN: "LOGIN",
  HOME: "HOME",
  SCORE: "SCORE",
  EXAM_SCHEDULE: "EXAM_SCHEDULE",
  CLASS_SCHEDULE: "CLASS_SCHEDULE",
  TUITION_BILL: "TUITION_BILL",
  TUITION_BILL_DETAIL: "TUITION_BILL_DETAIL",
  DASHBOARD: "DASHBOARD",
  SETTING: "SETTING",
  NOTIFICATION: "NOTIFICATION",
  CREDIT: "CREDIT",
};
